### ISSUE TITLE
migration script must explicitly list all files that are migrated

### ISSUE THREAD

**Issue by abadger** [ansible-community/collection_migration#201]
One requirement that has come out in the last two weeks is that every plugin that's migrated to a collection needs to be explicitly listed in BOTMETA.yml.  We can't use directories or wildcards for these.  This is because, once the content is removed from ansible/ansible, building docs for the removed content won't be able to tell what content used to exist in ansible/ansible without this information.

Here's an example of a BOTMETA.yml entry that the migrate script needs to be fixed to list all files individually:
```
 $modules/cloud/hcloud/: &id039
    keywords:
    - hcloud
    - hetzner cloud
    labels:
    - cloud
    - hcloud
    maintainers: $team_hcloud
    migrated_to: misc.glob
```

@jctanner and @gundalow discussed this and came to the conclusion that explicit listing of all files was the right way to go.
