### ISSUE TITLE
integration tests improperly rewritten

### ISSUE THREAD

**Issue by bcoca** [ansible-community/collection_migration#44]
see last line of excerpt of 
ansible_collections/microsoft/azure/tests/integration/targets/azure_rm_devtestlab/tasks/main.yml

``` yaml
  microsoft.azure.azure_rm_devtestlabartifactsource:
    resource_group: '{{ resource_group }}'
    lab_name: '{{ lab_name }}'
    name: '{{ artifacts_name }}'
    source_type: github
    folder_path: /tasks
    security_token: '{{ github_token }}'
    ansible._core.uri: https://github.com/Azure/azure_preview_modules.git
```

2 issues:
  * `uri:` option was being detected as a module (wrong)
  * ~~a module from _core was rewritten, it is supposed to skip those~~ FIXED in #47

**Comment by mkrizek** [comment]
Another examples of incorrent rewrite is:

https://github.com/ansible/ansible/blob/2da2da54f829d8aedec08bfac85c1a80d78be2fa/test/integration/targets/lineinfile/vars/main.yml#L1-L12

The `replace` key in the `test_regexp` dict is detected as a module.

**Comment by mkrizek** [comment]
@bcoca @webknjaz any of you have any thoughts about how to reliably detect "module name vs. option name" without building AI? :)

For example, say we want to move `uri` to a collection, how do we rewrite `uri` string only in the first case and not in the second:
```yaml
uri:
  url: http://www.example.com
```
vs.
```yaml
- name: Create (or update) DevTest Labs Artifacts Source
    azure_rm_devtestlabartifactsource:
      resource_group: myrg
      lab_name: mylab
      name: myartifacts
      uri: https://github.com/myself/myrepo.git
      source_type: github
      folder_path: /
      security_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I wonder how many occurrences of this problem are there. Maybe there are not that many that would justify spending too much time on this and fix that after migration.
